version: 0.0
os: linux
files:
  - source: /target/app.war
    destination: /opt/codedeploy-agent/deployment-root/

hooks:
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 300
  BeforeInstall:
    - location: scripts/echo_beforeinstall
      timeout: 300
  Install:
    - location: scripts/echo_beforeinstall
      timeout: 300
  AfterInstall:
    - location: scripts/echo_beforeinstall
      timeout: 300         
  ApplicationStart:
    - location: scripts/start_application
      timeout: 300
  ValidateService:
    - location: scripts/echo_beforeinstall
      timeout: 300  
