#!/bin/bash

set -e

CATALINA_HOME='/opt/apache-tomcat-8.5.35'
DEPLOY_TO_ROOT='true'

TEMP_STAGING_DIR='/opt/codedeploy-agent/deployment-root'
WAR_STAGED_LOCATION="$TEMP_STAGING_DIR/springboot-first-app-0.0.1-SNAPSHOT.war"

# In Tomcat, ROOT.war maps to the server root
if [[ "$DEPLOY_TO_ROOT" = 'true' ]]; then
    CONTEXT_PATH='springboot-first-app'
fi

# Remove unpacked application artifacts
if [[ -f $CATALINA_HOME/webapps/$CONTEXT_PATH.war ]]; then
    rm $CATALINA_HOME/webapps/$CONTEXT_PATH.war
fi
if [[ -d $CATALINA_HOME/webapps/$CONTEXT_PATH ]]; then
    rm -rfv $CATALINA_HOME/webapps/$CONTEXT_PATH
fi

# Copy the WAR file to the webapps directory
cp $WAR_STAGED_LOCATION $CATALINA_HOME/webapps/$CONTEXT_PATH.war


sudo systemctl start tomcat
